# Generated by Django 3.2 on 2022-05-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectionrequest', '0004_auto_20220522_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='connection_reason',
            field=models.CharField(choices=[('their weight', 'Weight'), ('depression', 'Depression'), ('grief', 'Grief'), ('their marriage', 'Marriage'), ('their physical wellbeing', 'Physical Wellbeing'), ('their finances', 'Finance'), ('loneliness', 'Loneliness'), ('their religion', 'Religion'), ('a Divorce', 'Divorce'), ('their gender identity', 'Gender Identity'), ('worries about death', 'Death'), ('anxiety', 'Anxiety'), ('their belief', 'Belief'), ('their mental health', 'Mental Health'), ('their health', 'Health'), ('their sexuality', 'Sexuality'), ('their relationships', 'Relationship'), ('loss', 'Loss')], max_length=30),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='relation',
            field=models.CharField(choices=[('work collegues', 'Work Collegues'), ('close friends', 'Close Friends'), ('friends', 'Friends'), ('family', 'Family')], max_length=30),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='response_decision',
            field=models.CharField(blank=True, choices=[('accept', 'Yes'), ('deny', 'No')], max_length=30, null=True),
        ),
    ]
